version: '3.8'
services:
  openldap:
    image: osixia/openldap:1.5.0
    restart: always
    container_name: openldap
    environment:
      LDAP_ORGANISATION: "Hikari Develop"
      LDAP_DOMAIN: "hikari-dev.com"
      LDAP_BASE_DN: "dc=hikari-dev,dc=com"
      LDAP_ADMIN_PASSWORD: "${LDAP_PASSWD}"
      LDAP_CONFIG_PASSWORD: "${LDAP_PASSWD}"
      LDAP_TLS: "false"
    ports:
      - "389:389"
