version: '3.8'
services:
  openldap:
    image: osixia/openldap:1.5.0
    restart: always
    container_name: openldap
    environment:
      LDAP_ORGANISATION: "Hikari Develop"
      LDAP_DOMAIN: "hikari-dev.com"
      LDAP_BASE_DN: "dc=hikari-dev,dc=com"
      LDAP_ADMIN_PASSWORD: "${LDAP_PASSWD}"
      LDAP_CONFIG_PASSWORD: "${LDAP_PASSWD}"

      LDAP_TLS: "true"
      LDAP_TLS_CRT_FILENAME: "ldap.crt"
      LDAP_TLS_KEY_FILENAME: "ldap.key"
      LDAP_TLS_DH_PARAM_FILENAME: "dhparam.pem"
      LDAP_TLS_CA_CRT_FILENAME: "ca.crt"
    ports:
      - "389:389"
